TARGET_EXEC ?= v06x

ARCH ?=
MT :=

SYSROOT :=
LIBROOT :=
OPENGL_LDFLAGS := -lGL
#SDL_STATIC := 1
BOOST_STATIC := 1

include common.mk

prefix ?= /usr/local

install:	$(BUILD_DIR)/$(TARGET_EXEC)
	install -d $(DESTDIR)$(prefix)/bin
	install $(BUILD_DIR)/$(TARGET_EXEC) $(DESTDIR)$(prefix)/bin
