TARGET_EXEC ?= v06x

ARCH ?=
MT := -mt

SYSROOT :=
LIBROOT :=
OPENGL_LDFLAGS := -framework OpenGL
SDL_LIBRARY_PATH := /usr/local/lib
BOOST_LIBRARY_PATH := /usr/local/lib
SDL_ALIBS := $(SDL_LIBRARY_PATH)/libSDL2.a $(SDL_LIBRARY_PATH)/libSDL2_image.a

include common.mk

prefix ?= /usr/local

install:	$(BUILD_DIR)/$(TARGET_EXEC)
	install -d $(DESTDIR)$(prefix)/bin
	install $(BUILD_DIR)/$(TARGET_EXEC) $(DESTDIR)$(prefix)/bin
