#pragma once

#include "android/keycodes.h"

typedef int SDL_Scancode;

enum {
    SDL_SCANCODE_F6 = AKEYCODE_F6,
    SDL_SCANCODE_F11 = AKEYCODE_F11,
    SDL_SCANCODE_F12 = AKEYCODE_F12,
    SDL_SCANCODE_PAUSE = AKEYCODE_MEDIA_PLAY_PAUSE,
    SDL_SCANCODE_LSHIFT = AKEYCODE_SHIFT_LEFT,
    SDL_SCANCODE_RSHIFT = AKEYCODE_SHIFT_RIGHT,
    SDL_SCANCODE_LCTRL = AKEYCODE_CTRL_LEFT,
    SDL_SCANCODE_RCTRL = AKEYCODE_CTRL_RIGHT,
    SDL_SCANCODE_LGUI = -1,
    SDL_SCANCODE_LALT = AKEYCODE_ALT_LEFT,
    SDL_SCANCODE_SPACE = AKEYCODE_SPACE,
    SDL_SCANCODE_SEMICOLON = AKEYCODE_SEMICOLON,
    SDL_SCANCODE_1 = AKEYCODE_1,
    SDL_SCANCODE_2 = AKEYCODE_2,
    SDL_SCANCODE_3 = AKEYCODE_3,
    SDL_SCANCODE_4 = AKEYCODE_4,
    SDL_SCANCODE_5 = AKEYCODE_5,
    SDL_SCANCODE_6 = AKEYCODE_6,
    SDL_SCANCODE_7 = AKEYCODE_7,
    SDL_SCANCODE_8 = AKEYCODE_8,
    SDL_SCANCODE_9 = AKEYCODE_9,
    SDL_SCANCODE_0 = AKEYCODE_0,
    SDL_SCANCODE_MINUS = AKEYCODE_MINUS,
    SDL_SCANCODE_SLASH = AKEYCODE_SLASH,
    SDL_SCANCODE_A = AKEYCODE_A,
    SDL_SCANCODE_B = AKEYCODE_B,
    SDL_SCANCODE_C = AKEYCODE_C,
    SDL_SCANCODE_D = AKEYCODE_D,
    SDL_SCANCODE_E = AKEYCODE_E,
    SDL_SCANCODE_F = AKEYCODE_F,
    SDL_SCANCODE_G = AKEYCODE_G,
    SDL_SCANCODE_H = AKEYCODE_H,
    SDL_SCANCODE_I = AKEYCODE_I,
    SDL_SCANCODE_J = AKEYCODE_J,
    SDL_SCANCODE_K = AKEYCODE_K,
    SDL_SCANCODE_L = AKEYCODE_L,
    SDL_SCANCODE_M = AKEYCODE_M,
    SDL_SCANCODE_N = AKEYCODE_N,
    SDL_SCANCODE_O = AKEYCODE_O,
    SDL_SCANCODE_P = AKEYCODE_P,
    SDL_SCANCODE_Q = AKEYCODE_Q,
    SDL_SCANCODE_R = AKEYCODE_R,
    SDL_SCANCODE_S = AKEYCODE_S,
    SDL_SCANCODE_T = AKEYCODE_T,
    SDL_SCANCODE_U = AKEYCODE_U,
    SDL_SCANCODE_V = AKEYCODE_V,
    SDL_SCANCODE_W = AKEYCODE_W,
    SDL_SCANCODE_X = AKEYCODE_X,
    SDL_SCANCODE_Y = AKEYCODE_Y,
    SDL_SCANCODE_Z = AKEYCODE_Z,

    SDL_SCANCODE_GRAVE = AKEYCODE_GRAVE,
    SDL_SCANCODE_RIGHTBRACKET = AKEYCODE_RIGHT_BRACKET,
    SDL_SCANCODE_BACKSLASH = AKEYCODE_BACKSLASH,
    SDL_SCANCODE_LEFTBRACKET = AKEYCODE_LEFT_BRACKET,
    SDL_SCANCODE_PERIOD = AKEYCODE_PERIOD,
    SDL_SCANCODE_EQUALS = AKEYCODE_EQUALS,
    SDL_SCANCODE_COMMA = AKEYCODE_COMMA,
    SDL_SCANCODE_APOSTROPHE = AKEYCODE_APOSTROPHE,

    SDL_SCANCODE_F5 = AKEYCODE_F5,
    SDL_SCANCODE_F4 = AKEYCODE_F4,
    SDL_SCANCODE_F3 = AKEYCODE_F3,
    SDL_SCANCODE_F2 = AKEYCODE_F2,
    SDL_SCANCODE_F1 = AKEYCODE_F1,
    SDL_SCANCODE_ESCAPE = AKEYCODE_ESCAPE,
    SDL_SCANCODE_F8 = AKEYCODE_F8, // СТР
    SDL_SCANCODE_F7 = AKEYCODE_F7, // ^\ ?

    SDL_SCANCODE_DOWN = AKEYCODE_DPAD_DOWN,
    SDL_SCANCODE_RIGHT = AKEYCODE_DPAD_RIGHT,
    SDL_SCANCODE_UP = AKEYCODE_DPAD_UP,
    SDL_SCANCODE_LEFT = AKEYCODE_DPAD_LEFT,
    SDL_SCANCODE_BACKSPACE = AKEYCODE_DEL,
    SDL_SCANCODE_RETURN = AKEYCODE_ENTER,
    SDL_SCANCODE_RALT = AKEYCODE_ALT_RIGHT,
    SDL_SCANCODE_TAB = AKEYCODE_TAB,
};

enum SDL_PixelFormat {
    SDL_PIXELFORMAT_ARGB8888,
    SDL_PIXELFORMAT_RGB888,
    SDL_PIXELFORMAT_BGR888,
    SDL_PIXELFORMAT_ABGR8888,
};

enum SDL_EventType {
    SDL_KEYDOWN,
    SDL_KEYUP,
    SDL_WINDOWEVENT,
    SDL_QUIT,

    SDL_WINDOWEVENT_RESIZED,
    SDL_WINDOWEVENT_EXPOSED,
    SDL_WINDOWEVENT_SIZE_CHANGED,
};

struct SDL_KeySym {
    SDL_Scancode scancode;
};

struct SDL_KeyboardEvent {
    SDL_KeySym keysym;
};

struct SDL_WindowEvent {
    SDL_EventType event;
};

struct SDL_Event {
    SDL_EventType type;
    union {
        SDL_KeyboardEvent key;
        SDL_WindowEvent window;
    };
};